find_package(GTest REQUIRED)
include(romea_add_gtest)

romea_add_gtest(test_kinematic_1FAS2FWD kinematic/test_kinematic_1FAS2FWD.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_kinematic_1FAS2RWD kinematic/test_kinematic_1FAS2RWD.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_kinematic_1FAS4WD kinematic/test_kinematic_1FAS4WD.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_kinematic_2AS4WD kinematic/test_kinematic_2AS4WD.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_kinematic_2FWS2RWD kinematic/test_kinematic_2FWS2RWD.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_kinematic_2FWS4WD kinematic/test_kinematic_2FWS4WD.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_kinematic_2FWS2FWD kinematic/test_kinematic_2FWS2FWD.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_kinematic_4WS4WD kinematic/test_kinematic_4WS4WD.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_kinematic_2WD kinematic/test_kinematic_2WD.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_command_limits kinematic/test_command_limits.cpp LIBRARIES ${PROJECT_NAME})

romea_add_gtest(test_simulation_control_1FAS2FWD simulation/test_simulation_1FAS2FWD.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_simulation_control_1FAS2RWD simulation/test_simulation_1FAS2RWD.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_simulation_control_1FAS4WD simulation/test_simulation_1FAS4WD.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_simulation_control_2AS4WD simulation/test_simulation_2AS4WD.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_simulation_control_2FWS2FWD simulation/test_simulation_2FWS2FWD.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_simulation_control_2FWS2RWD simulation/test_simulation_2FWS2RWD.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_simulation_control_2TD simulation/test_simulation_2TD.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_simulation_control_2THD simulation/test_simulation_2THD.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_simulation_control_2TTD simulation/test_simulation_2TTD.cpp LIBRARIES ${PROJECT_NAME})

romea_add_gtest(test_mobile_base_type info/test_mobile_base_type.cpp LIBRARIES ${PROJECT_NAME})
